/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    API_URL: process.env.API_URL,
    NAME: process.env.NAME,
    ADDRESS: process.env.ADDRESS,
    PIB: process.env.PIB,
    EMAIL: process.env.EMAIL,
    TELEPHONE: process.env.TELEPHONE,
    TELEPHONE2: process.env.TELEPHONE2,
    MB: process.env.MB,
    PIB: process.env.PIB,
    WORKTIME: process.env.WORKTIME,
    CAPTCHAKEY: process.env.CAPTCHAKEY,
    INSTAGRAM: process.env.INSTAGRAM,
    SHOW_CHECKOUT_SHIPPING_FORM: process.env.SHOW_CHECKOUT_SHIPPING_FORM,
  },
  images: {
    domains: [
      "scontent.cdninstagram.com",
      "api.tiedup.croonus.com",
      "video.cdninstagram.com",
      "192.168.1.223",
      "api.akt.croonus.com",
    ],
    minimumCacheTTL: 60 * 60 * 24 * 90,
  },
  redirects: async () => {
    return [
      {
        source: "/shop",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/personalizovana-dugmad-za-manzetne",
        destination: "/personalizovana-dugmad-za-manzetne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/ascot-kravate",
        destination: "/muskarci/ascot-kravate",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-category/bow-ties/",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/maramice",
        destination: "/muskarci/maramice",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/masne-sr",
        destination: "/muksarci/leptir-masne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/snale-za-kravatu",
        destination: "/muskarci/snale-za-kravatu",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/gde-kupiti-tied-up-proizvode",
        destination: "/gdekupiti",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/fotoaparat-leptir-masna-copy",
        destination: "/muzicke-note-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/kravate",
        destination: "/muskarci/kravate",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/gallery",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/salovi",
        destination: "/zene/salovi",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/beograd-leptir-masna",
        destination: "/beograd-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/leptir-masna-sa-dizajnom-po-zelji",
        destination: "/personalizovana-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kontakt",
        destination: "/kontakt",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-tag/scarfs/",
        destination: "/muskarci/salovi",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/crna-leptir-masna",
        destination: "/crna-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/personalizovana-kravata",
        destination: "/personalizovana-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/st-valentine-gift-set/",
        destination: "/st-valentine-poklon-set",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/classy-poklon-set",
        destination: "/classy-poklon-set",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-category/ties/",
        destination: "/muskarci/kravate",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/kum-nije-dugme-leptir-masna",
        destination: "/kum-nije-dugme-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/personalizovana-maramica-za-dzep-sakoa",
        destination: "/personalizovana-maramica-za-dzep-sakoa",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/crvena-leptir-masna",
        destination: "/crvena-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/braon-leptir-masna",
        destination: "/braon-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/americka-zastava-leptir-masna-2",
        destination: "/americka-zastava-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/zuta-leptir-masna",
        destination: "/zuta-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-category/ascot-ties/",
        destination: "/muskarci/ascot-kravate",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/razne-leptir-masne",
        destination: "/muskarci/leptir-masne/razne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-category/socks/",
        destination: "/muskarci/carape",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/star-wars-bow-tie-4/",
        destination: "/star-wars-leptir-masna-4",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/kasmir-manzetne-1",
        destination: "/muskarci/manzetne/kasmir-3",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/batman-kravata",
        destination: "/batman-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/cvetna-kravata-3",
        destination: "/cvetna-kravata-3",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/muzicke-note-carape",
        destination: "/muzicke-note-carape",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/rick-and-morty-bow-tie/",
        destination: "/rick-and-morty-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-category/cartoons/",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/avion-snala-za-kravatu",
        destination: "/avion-snala-za-kravatu",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/karirane-manzetne-8",
        destination: "/karirane-manzetne-8",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/star-wars-poklon-set",
        destination: "/star-wars-poklon-set",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/contact-us/",
        destination: "/kontakt/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-category/muvies-series/",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/sunder-bob-leptir-masna",
        destination: "/sunder-bob-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/zelena-leptir-masna",
        destination: "/zelena-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/only-fools-and-horses-bow-tie/",
        destination: "/mucke-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/zastava-spanije-leptir-masna",
        destination: "/zastava-spanije-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/muzicka-nota-snala-za-kravatu",
        destination: "/muzicka-nota-snala-za-kravatu",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/svetlo-plava-leptir-masna",
        destination: "/svetlo-plava-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/manzetne",
        destination: "/muskarci/manzetne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/tirkizno-plava-leptir-masna",
        destination: "/tirkizno-plava-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/mint-zelena-leptir-masna",
        destination: "/mint-zelena-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-category/retro/",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/greece-flag-bow-tie/",
        destination: "/grcka-zastava-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/spiderman-leptir-masna-2",
        destination: "/spiderman-leptir-masna-2",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/van-gogh-kravata",
        destination: "/van-gogh-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/star-wars-leptir-masna-2",
        destination: "/star-wars-leptir-masna-2",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/zastava-italije-leptir-masna",
        destination: "/zastava-italije-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/tied-up-casual-unisex-scarf-1/",
        destination: "/tied-up-casual-unisex-sal-1",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/brkovi-snala-za-kravatu",
        destination: "/brkovi-snala-za-kravatu",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/carape",
        destination: "/muskarci/carape",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/tied-up-casual-unisex-sal-1",
        destination: "/proizvod/tied-up-casual-unisex-sal-1",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/muske-majice",
        destination: "/muskarci/muske-majice",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/filmovi-serije-leptir-masne",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/betmen-carape",
        destination: "/betmen-carape",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-tag/retro-ties/",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/zenska-majica-good-vibes-only",
        destination: "/zenska-majica-good-vibes-only",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/rolling-stones-bow-tie/",
        destination: "/rolling-stones-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/matematicke-i-fizicke-formule-kravata",
        destination: "/matematicke-i-fizicke-formule-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/batman-tie/",
        destination: "/betmen-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/cvetna-ascot-kravata-6",
        destination: "/cvetna-ascot-kravata-6",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/tufnice-kravata-2",
        destination: "/tufnice-kravata-2",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/super-mario-bow-tie/",
        destination: "/super-mario-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/bordo-leptir-masna",
        destination: "/bordo-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/jednorog-leptir-masna",
        destination: "/jednorog-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/ascot-kravata-crna-patern-14",
        destination: "/ascot-kravata-crna-patern-14",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/brkovi-leptir-masna",
        destination: "/brkovi-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-category/tie-clips/",
        destination: "/muskarci/snale-za-kravatu",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/kasmir",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/betmen-leptir-masna-1",
        destination: "/betmen-leptir-masna-1",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/kosarkaska-leptir-masna",
        destination: "/kosarkaska-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/askot-kravata-bez-kasmir-sara-8",
        destination: "/askot-kravata-bez-kasmir-sara-8",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/star-wars-socks/",
        destination: "/star-wars-carape",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/manzetne/page/2",
        destination: "/muskarci/manzetne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/siidro-rever-cvetic",
        destination: "/siidro-rever-cvetic",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/poklon-set",
        destination: "/muskarci/poklon-set",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/klavir-kravata",
        destination: "/klavir-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-tag/school-socks/",
        destination: "/muskarci/carape/skola-2",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/star-wars-carape",
        destination: "/star-wars-carape",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/mali-princ-leptir-masna",
        destination: "/mali-princ-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/music-lovers-poklon-set",
        destination: "/music-lovers-poklon-set",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/carape-sa-biciklom",
        destination: "/carape-sa-biciklom",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-tag/men/",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/engleska-zastava-leptir-masna",
        destination: "/engleska-zastava-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/zastava-bosne-i-hercegovine-leptir-masna",
        destination: "/zastava-bosne-i-hercegovine-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/spiderman-boe-tie-2/",
        destination: "/spiderman-leptir-masna-2",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/rever-cvetici",
        destination: "/muskarci/rever-cvetici",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/batman-bow-tie-1/",
        destination: "/batman-leptir-masna-2",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/cvetna-kravata-5",
        destination: "/cvetna-kravata-5",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/retro-leptir-masne",
        destination: "/muskarci/leptir-masne/retro",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-category/custom/",
        destination: "/personalizovano",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/squidward-tentacles-bow-tie/",
        destination: "/lignjoslav-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/mickey-mouse-leptir-masna",
        destination: "/mickey-mouse-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/karirana-kravata-6",
        destination: "/karirana-kravata-6",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/superman-bow-tie-1/",
        destination: "/superman-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/sidro-manzetne",
        destination: "/sidro-manzetne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-category/gift-sets/",
        destination: "/muskarci/poklon-set",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/ninja-turtle-bow-tie/",
        destination: "/nindza-kornjace-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/patern-ascot-kravata-1",
        destination: "/patern-ascot-kravata-1",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/cvetna-kravata-10-copy-copy",
        destination: "/cvetna-kravata-10-2",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/wonder-woman-bow-tie/",
        destination: "/wonder-woman-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-category/super-heroes/",
        destination: "/muskarci/leptir-masne/crtaci",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/belgrade-bow-tie/",
        destination: "/beograd-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/ananas-kravata",
        destination: "/ananas-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/ascot-kravate/page/2",
        destination: "/muskarci/ascot-kravate",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/personalizovana",
        destination: "/personalizovano",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/sidro-kravata",
        destination: "/sidro-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/kasmir-kravata-9",
        destination: "/kasmir-kravata-9",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/anchor-ascot-tie/",
        destination: "/sidro-ascot-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/prens-de-gal-manzetne",
        destination: "/prens-de-gal-manzetne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/star-wars-bow-tie-1/",
        destination: "/star-wars-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/jednobojne-leptir-masne",
        destination: "/muskarci/leptir-masne/jednobojne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/pivo-leptir-masna-1",
        destination: "/pivo-leptir-masna-1",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/ascot-kravata-zelena-tufnice-6",
        destination: "/ascot-kravata-zelena-tufnice-6",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/novogodisnja-leptir-masna-1",
        destination: "/novogodisnja-leptir-masna-1",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/superman-poklon-set",
        destination: "/superman-poklon-set",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/bez-leptir-masna",
        destination: "/bez-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/superman-carape",
        destination: "/superman-carape",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/retro-poklon-set",
        destination: "/retro-poklon-set",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/zenska-majica-freedom",
        destination: "/zenska-majica-freedom",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/super-heroji-leptir-masne",
        destination: "/muskarci/leptir-masne/super-heroji",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/zenska-majica-easy-with-me",
        destination: "/zenska-majica-easy-with-me",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/gustav-klimt-bow-tie/",
        destination: "/gustav-klimt-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/pruge-kravata-2",
        destination: "/pruge-kravata-2",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/kasmir-ascot-kravate",
        destination: "/muskarci/ascot-kravate/kasmir-6",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/crvene-manzetne",
        destination: "/crvene-manzetne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/panda-leptir-masna",
        destination: "/panda-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/zivotinje-kravate",
        destination: "/muskarci/kravate/zivotinje-2",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/spiderman-lleptir-masna-1",
        destination: "/spiderman-lleptir-masna-1",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/batman-leptir-masna-2",
        destination: "/batman-leptir-masna-2",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/star-wars-bow-tie",
        destination: "/star-wars-bow-tie",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/zastava-nemacke-leptir-masna",
        destination: "/zastava-nemacke-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/zastava-ceske-republike-leptir-masna",
        destination: "/zastava-ceske-republike-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-tag/cartoons-bow-ties/",
        destination: "/muskarci/leptir-masne/crtaci",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/gallery/",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/superman-gift-set/",
        destination: "/superman-poklon-set",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/retro-leptir-masna-2",
        destination: "/retro-leptir-masna-2",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/noc-vestica-leptir-masna-3",
        destination: "/noc-vestica-leptir-masna-3",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/muzicke-note-maramica",
        destination: "/muzicke-note-maramica",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/naocare-snale-za-kravatu",
        destination: "/naocare-snale-za-kravatu",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-tag/map-bow-ties/",
        destination: "/muskarci/leptir-masne/mape",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/muzika-leptir-masne",
        destination: "/muskarci/leptir-masne/muzika",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/batman-snala-za-kravatu",
        destination: "/batman-snala-za-kravatu",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/spiderman-boe-tie-1/",
        destination: "/spiderman-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/super-heroji",
        destination: "/muskarci/leptir-masne/super-heroji",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/matematicke-i-fizicke-formule-leptir-masna-2",
        destination: "/matematicke-i-fizicke-formule-leptir-masna-2",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/masne-sr/page/2",
        destination: "/muskarci/leptir-masne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/muzicke-note-manzetne",
        destination: "/muzicke-note-manzetne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/dollar-tie/",
        destination: "/dolar-leptir-masna-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-category/pocket-square/",
        destination: "/muskarci/maramice",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/teget-leptir-masna",
        destination: "/teget-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/carape-super-heroji",
        destination: "/muskarci/carape/super-heroji-2",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/batman-tie-clip/",
        destination: "/batman-snala-za-kravatu",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/mapa-sveta-kravata",
        destination: "/mapa-sveta-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/kraljevsko-plava-leptir-masna",
        destination: "/kraljevsko-plava-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/novogodisnje-jelke-carape",
        destination: "/novogodisnje-jelke-carape",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/muske-majice",
        destination: "/muskarci/muske-majice",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/karirane-kravate",
        destination: "/muskarci/kravate/karirane",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/pattern-black-socks/",
        destination: "/patern-crne-carape",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/tufnice",
        destination: "/muskarci/kravate/tufnice",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/serbian-flag-bow-tie/",
        destination: "/zastava-srbije-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/kasmir-kravata-7-copy-2",
        destination: "/kasmir-kravata-7",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/prens-de-gal-leptir-masna",
        destination: "/prens-de-gal-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/klavir-leptir-masna-2",
        destination: "/klavir-leptir-masna-2",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/kasmir-kravata-7-copy",
        destination: "/kasmir-kravata-7",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/tufnice-kravata-3",
        destination: "/tufnice-kravata-3",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/south-parkbow-tie/",
        destination: "/south-park-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/trol-leptir-masna",
        destination: "/trol-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/biciklice-leptir-masna",
        destination: "/biciklice-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/salovi/page/2",
        destination: "/zene/salovi",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/cvetna-kravata-10",
        destination: "/cvetna-kravata-10",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/tufnice-leptir-masna-1",
        destination: "/tufnice-leptir-masna-1",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/tufnice-kravata-6-copy-2",
        destination: "/tufnice-kravata-6",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/macka-leptir-masna-1",
        destination: "/macka-leptir-masna-1",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/karirana-leptir-masna-6",
        destination: "/karirana-leptir-masna-6",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/novogodisnji-poklon-set-4",
        destination: "/novogodisnji-poklon-set-4",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/masne-sr/page/7",
        destination: "/muskarci/leptir-masne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/superman-kravata",
        destination: "/superman-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/gustav-klimt-kravata",
        destination: "/gustav-klimt-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/rubikova-kocka-leptir-masna",
        destination: "/rubikova-kocka-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/sidro-leptir-masna",
        destination: "/sidro-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/personalizovana-leptir-masna",
        destination: "/personalizovano/personalizovana-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/personalizovana-dugmad-za-manzetne",
        destination: "/personalizovano/personalizovana-dugmad-za-manzetne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/macka-kravata-1",
        destination: "/macka-kravata-1",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/vino-leptir-masna",
        destination: "/vino-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/karirana-kravata-3",
        destination: "/karirana-kravata-3",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/cvetna-ascot-kravata-6/",
        destination: "/cvetna-ascot-kravata-6",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-tag/socks/",
        destination: "/muskarci/carape",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-tag/school-ties/",
        destination: "/muskarci/kravate/skola",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/dolar-leptir-masna",
        destination: "/dolar-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/cvetna-maramica-5",
        destination: "/cvetna-maramica-5",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/matematicke-i-fizicke-formule-carape",
        destination: "/matematicke-i-fizicke-formule-carape",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/zivotinje-leptir-masne-sr",
        destination: "/muskarci/leptir-masne/zivotinje",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/zute-manzetne",
        destination: "/zute-manzetne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/kasmir-maramica-1",
        destination: "/kasmir-maramica-1",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/fudbalska-leptir-masna",
        destination: "/fudbalska-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/mathematical-and-physical-formula-tie/",
        destination: "/matematicke-i-fizicke-formule-carape",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/urbani-mornar-poklon-set",
        destination: "/urbani-mornar-poklon-set",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/retro-rever-cvetic-5",
        destination: "/retro-rever-cvetic-5",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/sport-leptir-masne",
        destination: "/muskarci/leptir-masne/sport",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/fotoaparati-kravata",
        destination: "/fotoaparati-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/patern-crne-carape-copy",
        destination: "/patern-crne-carape-copy",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/montenegro-flag-bow-tie/",
        destination: "/crnogorska-zastava-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/retro-kravata-4",
        destination: "/retro-kravata-4",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/motori-leptir-masna",
        destination: "/motori-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/south-park-leptir-masna",
        destination: "/south-park-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/cvetne",
        destination: "/muskarci/kravate/cvetne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/hemijska-leptir-masna",
        destination: "/hemijska-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-category/bow-ties/page/17/",
        destination: "/muskarci/leptir-masne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product-category/cufflinks/",
        destination: "/muskarci/manzetne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/star-wars-leptir-masna-6",
        destination: "/star-wars-leptir-masna-6",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/azbuka-leptir-masna",
        destination: "/azbuka-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/ascot-tie-red-cashmere-designe-9/",
        destination: "/askot-kravata-crvena-kasmir-sara-9",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/bordeaux-cufflinks/",
        destination: "/bordo-manzetne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/tirkizno-plave-manzetne",
        destination: "/tirkizno-plave-manzetne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/jednobojne-leptir-masne/page/2",
        destination: "/muskarci/leptir-masne/jednobojne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/dinosaurusi-leptir-masna",
        destination: "/dinosaurusi-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/patern-leptir-masna-21",
        destination: "/patern-leptir-masna-21",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/lisce-kravata",
        destination: "/lisce-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/kategorija-proizvoda/cvetne/page/2",
        destination: "/muskarci/kravate/cvetne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/dark-side-poklon-set",
        destination: "/dark-side-poklon-set",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/sidro-kravata&clang=sr",
        destination: "/sidro-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/tied-up-casual-unisex-sal-18",
        destination: "/tied-up-casual-unisex-sal-18",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/mapa-sveta-kravata/",
        destination: "/mapa-sveta-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/denim-ascot-tie-1/",
        destination: "/teksas-ascot-kravata-1",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/fotoaparat-maramica",
        destination: "/fotoaparat-maramica",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/zenske-majice",
        destination: "/zene/zenske-majice",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/hulk-leptir-masna",
        destination: "/hulk-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/patern-kravata-12",
        destination: "/patern-kravata-12",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/la-linea-leptir-masna",
        destination: "/la-linea-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/iron-man-leptir-masna",
        destination: "/iron-man-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/flamingosi-kravata",
        destination: "/flamingosi-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/mapa-kravata",
        destination: "/mapa-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/cvetni-rever-cvetici",
        destination: "/muskarci/rever-cvetici/cvetni",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/biciklice-kravata",
        destination: "/biciklice-kravata",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/rapsody-poklon-set-2",
        destination: "/rapsody-poklon-set-2",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/oznaka-proizvoda/umetnost-kravate",
        destination: "/muskarci/kravate/umetnost-2",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/patern-kravata-2",
        destination: "/patern-kravata-2",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/brazil-flag-bow-tie/",
        destination: "/brazilska-zastava-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/zastava-rusije-leptir-masna",
        destination: "/zastava-rusije-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/novogodisnja-leptir-masna-5",
        destination: "/novogodisnja-leptir-masna-5",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/shop/",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/bosnia-and-herzegovina-flag-bow-tie/",
        destination: "/zastava-bosne-i-hercegovine-leptir-masna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/daily-night-gift-set/",
        destination: "/daily-night-poklon-set",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/proizvod/sidro-manzetne",
        destination: "/sidro-manzetne",
        permanent: true,
        statusCode: 301,
      },
    ];
  },
};

module.exports = nextConfig;
